version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres-fact
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: facturacion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build: .
    container_name: api-fact
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/facturacion
      PORT: 3000
      HACIENDA_CLIENT_ID: api-stag
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data: